# Path to pretrained model or model identifier from huggingface.co/models
model_name_or_path: "bert-base-cased"

per_gpu_train_batch_size: 32

per_gpu_eval_batch_size: 64

learning_rate: !!float 5e-5

weight_decay: !!float 5e-4

hidden_dropout_prob: 0.5

num_epochs: 3.0

# If set, total number of training steps to perform. Conflicts with num_epochs.
max_steps: 30000

# Linear warmup over warmup_steps
warmup_steps: 1000

# log every n steps
log_steps: 1000

# Validate every n steps
eval_steps: 1000

early_stopping: true

# save model every n steps
save_steps: 1000

# save last n models
save_total_limit: 5

# checks n more steps before early stopping
early_stopping_patience: 5
